# Generated by Django 5.2.15 on 2026-07-02 08:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_code', models.CharField(max_length=10, unique=True)),
                ('support_email', models.EmailField(max_length=254, unique=True)),
                ('support_phone', models.CharField(max_length=15, unique=True)),
                ('headquarters', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
                'ordering': ['company_name'],
            },
        ),
    ]
