# Generated by Django 5.2.15 on 2026-07-02 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_type', models.CharField(choices=[('AC_SEATER', 'AC Seater'), ('AC_SLEEPER', 'AC Sleeper'), ('NON_AC_SEATER', 'Non-AC Seater'), ('NON_AC_SLEEPER', 'Non-AC Sleeper')], max_length=20)),
                ('total_seats', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='operators.operator')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['bus_number'],
            },
        ),
    ]
