# Generated by Django 5.2.15 on 2026-07-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
