# Generated by Django 5.2.15 on 2026-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_bus_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='deck_count',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Single Deck'), (2, 'Double Deck')], default=1),
        ),
        migrations.AddField(
            model_name='bus',
            name='seat_layout',
            field=models.CharField(default='2+2', help_text="Seats-per-row pattern, e.g. '2+2' (seater) or '2+1' (sleeper)", max_length=10),
        ),
    ]
