# Generated by Django 5.2.15 on 2026-07-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
