# Generated by Django 5.2.15 on 2026-07-08 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('trips', '0002_trip_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_booking', to='bookings.booking')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_booking', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Seat Booking',
                'verbose_name_plural': 'Seat Bookings',
                'ordering': ['seat_number'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'seat_number'), name='unique_trip_seat')],
            },
        ),
    ]
